import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getCodeSnippetsByLocation } from "@/lib/codeSnippets/repo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const snippets = await getCodeSnippetsByLocation();
  // <head> can only take `children` OR `dangerouslySetInnerHTML`, never both,
  // and a Code Snippet's `code` already carries its own tags (<script>,
  // <style>, <meta>, ...), so those tags must land as head's *direct*
  // children — this doesn't fight Next's own metadata tags (title, etc. from
  // `metadata` above), which are inserted via React's hoistable head
  // mechanism independently of this element's own children/props.
  const headHtml = [snippets.after_head_open, snippets.before_head_end].filter(Boolean).join("\n");

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {headHtml && <head suppressHydrationWarning dangerouslySetInnerHTML={{ __html: headHtml }} />}
      <body className="min-h-full flex flex-col">
        {/* display:contents so an injected snippet never becomes its own box
            in body's flex layout. */}
        {snippets.after_body_open && (
          <div
            style={{ display: "contents" }}
            suppressHydrationWarning
            dangerouslySetInnerHTML={{ __html: snippets.after_body_open }}
          />
        )}
        {children}
        {snippets.before_body_end && (
          <div
            style={{ display: "contents" }}
            suppressHydrationWarning
            dangerouslySetInnerHTML={{ __html: snippets.before_body_end }}
          />
        )}
      </body>
    </html>
  );
}
