/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload Config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Page {
  id: number;
  title: string;
  slug: string;
  metaDescription?: string | null;
  shareImage?: (string | number | Media) | null;
  html?: string | null;
  css?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    } | null;
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    } | null;
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    } | null;
  } | null;
}
export interface CategoriesDoc {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: number;
  roles: 'super-admin' | 'admin' | 'editor' | 'customer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt: string;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
export interface Blog {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug: string;
  category?: (string | number | CategoriesDoc) | null;
  tags?: string[] | null;
  featured?: boolean | null;
  visibility?: ('public' | 'password' | 'private') | null;
  postPassword?: string | null;
  excerpt?: string | null;
  coverImage?: (string | number | Media) | null;
  author?: (string | number | User) | null;
  publishedAt?: string | null;
  metaDescription?: string | null;
  shareImage?: (string | number | Media) | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
export interface Embed {
  url: string;
  provider?: string | null;
  html?: string | null;
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
export interface Comment {
  id: number;
  post: string | number | Blog;
  parent?: (string | number | Comment) | null;
  authorName: string;
  authorEmail: string;
  authorUrl?: string | null;
  content: string;
  status?: ('pending' | 'approved' | 'spam' | 'trash') | null;
  updatedAt: string;
  createdAt: string;
}
export interface Menu {
  id: number;
  name: string;
  items?: Link[] | null;
  updatedAt: string;
  createdAt: string;
}
export interface Link {
  label: string;
  linkType?: ('page' | 'post' | 'url') | null;
  page?: (string | number | Page) | null;
  post?: (string | number | Blog) | null;
  url?: string | null;
  children?:
    | {
        label: string;
        linkType?: ('page' | 'post' | 'url') | null;
        page?: (string | number | Page) | null;
        post?: (string | number | Blog) | null;
        url?: string | null;
        id: string;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'link';
}
export interface Template {
  id: number;
  name: string;
  collection: 'blog' | 'products' | 'house-designs';
  kind: 'detail' | 'index';
  html?: string | null;
  css?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Component {
  id: number;
  name: string;
  category:
    | 'header'
    | 'footer'
    | 'hero'
    | 'feature'
    | 'card'
    | 'cta'
    | 'pricing'
    | 'form'
    | 'slider'
    | 'custom';
  customCategory?: string | null;
  thumbnail?: (string | number | Media) | null;
  html?: string | null;
  css?: string | null;
  js?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Style {
  id: number;
  name: string;
  slug: string;
  category: 'Color' | 'Typography Scale' | 'Spacing / Container' | 'Border Radius & Shadow';
  colorValue?: string | null;
  typeScalePreset?:
    | (
        | 'Display Large'
        | 'Display Medium'
        | 'Display Small'
        | 'H1'
        | 'H2'
        | 'H3'
        | 'H4'
        | 'H5'
        | 'H6'
        | 'Body Large'
        | 'Body Base'
        | 'Body Small'
        | 'Caption'
        | 'Overline / Eyebrow'
        | 'Button / Label'
        | 'Code / Monospace'
        | 'Custom'
      )
    | null;
  fontSourceType?: ('Google Font URL' | 'Custom File Upload' | 'System Font Family Name') | null;
  googleFontUrl?: string | null;
  customFontFile?: (string | number | Media) | null;
  fontFamily?: string | null;
  fontSize?: string | null;
  fontWeight?: ('100' | '300' | '400' | '500' | '600' | '700' | '800' | '900') | null;
  lineHeight?: string | null;
  letterSpacing?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface HouseDesign {
  id: number;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  garage?: number | null;
  houseSize?: string | null;
  images?: (string | number | Media)[] | null;
  floorplans?: (string | number | Media)[] | null;
  aiVideoUrl?: string | null;
  brochure?: (string | number | Media) | null;
  metaDescription?: string | null;
  shareImage?: (string | number | Media) | null;
  updatedAt: string;
  createdAt: string;
}
export interface Form {
  id: number;
  title: string;
  fields?: (Text | Email | Textarea | Select)[] | null;
  submitButtonLabel?: string | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
export interface Text {
  name: string;
  label: string;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
export interface Email {
  name: string;
  label: string;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'email';
}
export interface Textarea {
  name: string;
  label: string;
  required?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textarea';
}
export interface Select {
  name: string;
  label: string;
  required?: boolean | null;
  options?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'select';
}
export interface FormSubmission {
  id: number;
  form: string | number | Form;
  submissionData: {
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
export interface CodeSnippet {
  id: number;
  title: string;
  status: 'active' | 'disabled';
  location: 'after_head_open' | 'before_head_end' | 'after_body_open' | 'before_body_end';
  codeType?: ('html' | 'javascript' | 'css') | null;
  code: string;
  priority?: number | null;
  targetPages?: ('all_pages' | 'specific_pages') | null;
  updatedAt: string;
  createdAt: string;
}
export interface PageView {
  id: number;
  path: string;
  visitorId?: string | null;
  updatedAt: string;
  createdAt: string;
}
export interface Product {
  id: number;
  inventory?: number | null;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?: (string | number | Media)[] | null;
  priceInUSD?: {
    priceInUSDEnabled?: boolean | null;
    priceInUSD?: number | null;
  } | null;
  priceInEUR?: {
    priceInEUREnabled?: boolean | null;
    priceInEUR?: number | null;
  } | null;
  priceInGBP?: {
    priceInGBPEnabled?: boolean | null;
    priceInGBP?: number | null;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
export interface OrderStatus {
  processing: 'processing';
  completed: 'completed';
  cancelled: 'cancelled';
}
export interface Order {
  id: number;
  items?:
    | {
        product?: (string | number | Product) | null;
        quantity?: number | null;
        id?: string | null;
      }[]
    | null;
  customer?: (string | number | User) | null;
  customerEmail?: string | null;
  transactions?: (string | number)[] | null;
  status?: OrderStatus | null;
  updatedAt: string;
  createdAt: string;
}
export interface Settings {
  id: number;
  homepage?: (string | number | Page) | null;
  primaryMenu?: (string | number | Menu) | null;
  footerMenu?: (string | number | Menu) | null;
  dashboard?: {
    widgets?: ('site_traffic' | 'form_submissions' | 'conversions' | 'comments')[] | null;
  };
  conversions?: {
    formSubmissions?: boolean | null;
    sales?: boolean | null;
    goals?:
      | {
          label: string;
          path: string;
          id?: string | null;
        }[]
      | null;
  };
  logoLight?: (string | number | Media) | null;
  logoDark?: (string | number | Media) | null;
  favicon?: (string | number | Media) | null;
  typography?: {
    fontProvider: 'google_fonts' | 'custom_upload';
    googleFontUrl?: string | null;
    fontFamilyName?: string | null;
    customFontLibrary?:
      | {
          label: string;
          fontFamilyName: string;
          fontFile: string | number | Media;
          fontWeight?: ('100' | '300' | '400' | '500' | '600' | '700') | null;
          fontStyle?: ('normal' | 'italic') | null;
          id?: string | null;
        }[]
      | null;
    activeCustomFont?: string | null;
    applyToAdminUI?: boolean | null;
  };
  adminPrimaryColor?: string | null;
  adminPrimaryButtonText?: string | null;
  adminFocusColor?: string | null;
  lightMainBackground?: string | null;
  lightCardBackground?: string | null;
  lightBaseText?: string | null;
  lightMutedText?: string | null;
  lightBorderColor?: string | null;
  lightSidebarBackground?: string | null;
  lightSidebarText?: string | null;
  darkMainBackground?: string | null;
  darkCardBackground?: string | null;
  darkBaseText?: string | null;
  darkMutedText?: string | null;
  darkBorderColor?: string | null;
  darkSidebarBackground?: string | null;
  darkSidebarText?: string | null;
  stripe?: {
    enabled?: boolean | null;
    mode?: ('test' | 'live') | null;
    publishableKey?: string | null;
    secretKey?: string | null;
    webhookSecret?: string | null;
  };
  paypal?: {
    enabled?: boolean | null;
    mode?: ('test' | 'live') | null;
    clientId?: string | null;
    publishableKey?: string | null;
    secretKey?: string | null;
    webhookSecret?: string | null;
  };
  square?: {
    enabled?: boolean | null;
    mode?: ('test' | 'live') | null;
    locationId?: string | null;
    publishableKey?: string | null;
    secretKey?: string | null;
    webhookSecret?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
export interface ThemeBuilder {
  id: number;
  header?: {
    mode?: ('DEFAULT_COMPONENT' | 'SAVED_TEMPLATE' | 'CUSTOM_BUILD' | 'NONE') | null;
    template?: (string | number | Component) | null;
    html?: string | null;
    css?: string | null;
  };
  footer?: {
    mode?: ('DEFAULT_COMPONENT' | 'SAVED_TEMPLATE' | 'CUSTOM_BUILD' | 'NONE') | null;
    template?: (string | number | Component) | null;
    html?: string | null;
    css?: string | null;
  };
  customRules?:
    | {
        targetPages: (string | number | Page)[];
        header?: {
          mode?: ('DEFAULT_COMPONENT' | 'SAVED_TEMPLATE' | 'CUSTOM_BUILD' | 'NONE') | null;
          template?: (string | number | Component) | null;
          html?: string | null;
          css?: string | null;
        };
        footer?: {
          mode?: ('DEFAULT_COMPONENT' | 'SAVED_TEMPLATE' | 'CUSTOM_BUILD' | 'NONE') | null;
          template?: (string | number | Component) | null;
          html?: string | null;
          css?: string | null;
        };
        id: string;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Widgets {
  id: number;
  areas?:
    | {
        area: 'sidebar' | 'footer_1' | 'footer_2' | 'footer_3';
        items?: (Heading | RichText | RecentPosts | Categories | SearchBox | WidgetsForm | Html)[] | null;
        id: string;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface Heading {
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
export interface RichText {
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
export interface RecentPosts {
  count?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'recentPosts';
}
export interface Categories {
  id?: string | null;
  blockName?: string | null;
  blockType: 'categories';
}
export interface SearchBox {
  id?: string | null;
  blockName?: string | null;
  blockType: 'searchBox';
}
export interface WidgetsForm {
  form: string | number | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
export interface Html {
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'html';
}
export interface Config {
  collections: {
    pages: Page;
    blog: Blog;
    categories: CategoriesDoc;
    comments: Comment;
    menus: Menu;
    templates: Template;
    components: Component;
    styles: Style;
    'house-designs': HouseDesign;
    forms: Form;
    'form-submissions': FormSubmission;
    'code-snippets': CodeSnippet;
    'page-views': PageView;
    users: User;
    media: Media;
    products: Product;
    orders: Order;
  };
  globals: {
    settings: Settings;
    'theme-builder': ThemeBuilder;
    widgets: Widgets;
  };
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
