// Auto-generated by Payload CMS — maps admin.components string references
// to their actual imports. Payload's own `generate:importmap` CLI can't run
// in this project (richtext-lexical's top-level-await ESM export breaks the
// CLI's CJS require), so this is maintained by hand. Keys must exactly match
// the "path#ExportName" strings used in payload.config.ts / collection configs.
import { AskaNav } from "@/components/admin/Nav";
import { Logo, Icon } from "@/components/admin/Logo";
import { AskaDashboard } from "@/components/admin/dashboard/AskaDashboard";
import { RichTextStyles } from "@/components/admin/RichTextStyles";
import { ViewBlogLink, ViewPageLink } from "@/components/admin/ViewLink";
import { EditPageVisuallyLink, EditTemplateVisuallyLink } from "@/components/admin/EditVisuallyLink";

export const importMap = {
  "@/components/admin/Nav#AskaNav": AskaNav,
  "@/components/admin/Logo#Logo": Logo,
  "@/components/admin/Logo#Icon": Icon,
  "@/components/admin/dashboard/AskaDashboard#AskaDashboard": AskaDashboard,
  "@/components/admin/RichTextStyles#RichTextStyles": RichTextStyles,
  "@/components/admin/ViewLink#ViewBlogLink": ViewBlogLink,
  "@/components/admin/ViewLink#ViewPageLink": ViewPageLink,
  "@/components/admin/EditVisuallyLink#EditPageVisuallyLink": EditPageVisuallyLink,
  "@/components/admin/EditVisuallyLink#EditTemplateVisuallyLink": EditTemplateVisuallyLink,
};
