import { Logo as Logo_0, Icon as Icon_0 } from "@/components/admin/Logo";
import { AskaNav as AskaNav_0 } from "@/components/admin/Nav";
import {
  ViewPageLink as ViewPageLink_0,
  ViewBlogLink as ViewBlogLink_0,
  ViewProductLink as ViewProductLink_0,
} from "@/components/admin/ViewLink";
import {
  EditPageVisuallyLink as EditPageVisuallyLink_0,
  EditTemplateVisuallyLink as EditTemplateVisuallyLink_0,
} from "@/components/admin/EditVisuallyLink";
import { AskaDashboard as AskaDashboard_0 } from "@/components/admin/dashboard/AskaDashboard";
import {
  RscEntryLexicalCell as RscEntryLexicalCell_1,
  RscEntryLexicalField as RscEntryLexicalField_1,
  LexicalDiffComponent as LexicalDiffComponent_1,
} from "@payloadcms/richtext-lexical/rsc";
import {
  AlignFeatureClient as AlignFeatureClient_1,
  BlockquoteFeatureClient as BlockquoteFeatureClient_1,
  BoldFeatureClient as BoldFeatureClient_1,
  ChecklistFeatureClient as ChecklistFeatureClient_1,
  FixedToolbarFeatureClient as FixedToolbarFeatureClient_1,
  HeadingFeatureClient as HeadingFeatureClient_1,
  HorizontalRuleFeatureClient as HorizontalRuleFeatureClient_1,
  IndentFeatureClient as IndentFeatureClient_1,
  InlineCodeFeatureClient as InlineCodeFeatureClient_1,
  InlineToolbarFeatureClient as InlineToolbarFeatureClient_1,
  ItalicFeatureClient as ItalicFeatureClient_1,
  LinkFeatureClient as LinkFeatureClient_1,
  OrderedListFeatureClient as OrderedListFeatureClient_1,
  ParagraphFeatureClient as ParagraphFeatureClient_1,
  RelationshipFeatureClient as RelationshipFeatureClient_1,
  StrikethroughFeatureClient as StrikethroughFeatureClient_1,
  SubscriptFeatureClient as SubscriptFeatureClient_1,
  SuperscriptFeatureClient as SuperscriptFeatureClient_1,
  UnderlineFeatureClient as UnderlineFeatureClient_1,
  UnorderedListFeatureClient as UnorderedListFeatureClient_1,
  UploadFeatureClient as UploadFeatureClient_1,
} from "@payloadcms/richtext-lexical/client";

export const importMap = {
  "@/components/admin/Logo#Logo": Logo_0,
  "@/components/admin/Logo#Icon": Icon_0,
  "@/components/admin/Nav#AskaNav": AskaNav_0,
  "@/components/admin/ViewLink#ViewPageLink": ViewPageLink_0,
  "@/components/admin/ViewLink#ViewBlogLink": ViewBlogLink_0,
  "@/components/admin/ViewLink#ViewProductLink": ViewProductLink_0,
  "@/components/admin/EditVisuallyLink#EditPageVisuallyLink": EditPageVisuallyLink_0,
  "@/components/admin/EditVisuallyLink#EditTemplateVisuallyLink": EditTemplateVisuallyLink_0,
  "@/components/admin/dashboard/AskaDashboard#AskaDashboard": AskaDashboard_0,
  "@payloadcms/richtext-lexical/rsc#RscEntryLexicalCell": RscEntryLexicalCell_1,
  "@payloadcms/richtext-lexical/rsc#RscEntryLexicalField": RscEntryLexicalField_1,
  "@payloadcms/richtext-lexical/rsc#LexicalDiffComponent": LexicalDiffComponent_1,
  "@payloadcms/richtext-lexical/client#AlignFeatureClient": AlignFeatureClient_1,
  "@payloadcms/richtext-lexical/client#BlockquoteFeatureClient": BlockquoteFeatureClient_1,
  "@payloadcms/richtext-lexical/client#BoldFeatureClient": BoldFeatureClient_1,
  "@payloadcms/richtext-lexical/client#ChecklistFeatureClient": ChecklistFeatureClient_1,
  "@payloadcms/richtext-lexical/client#FixedToolbarFeatureClient": FixedToolbarFeatureClient_1,
  "@payloadcms/richtext-lexical/client#HeadingFeatureClient": HeadingFeatureClient_1,
  "@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient": HorizontalRuleFeatureClient_1,
  "@payloadcms/richtext-lexical/client#IndentFeatureClient": IndentFeatureClient_1,
  "@payloadcms/richtext-lexical/client#InlineCodeFeatureClient": InlineCodeFeatureClient_1,
  "@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient": InlineToolbarFeatureClient_1,
  "@payloadcms/richtext-lexical/client#ItalicFeatureClient": ItalicFeatureClient_1,
  "@payloadcms/richtext-lexical/client#LinkFeatureClient": LinkFeatureClient_1,
  "@payloadcms/richtext-lexical/client#OrderedListFeatureClient": OrderedListFeatureClient_1,
  "@payloadcms/richtext-lexical/client#ParagraphFeatureClient": ParagraphFeatureClient_1,
  "@payloadcms/richtext-lexical/client#RelationshipFeatureClient": RelationshipFeatureClient_1,
  "@payloadcms/richtext-lexical/client#StrikethroughFeatureClient": StrikethroughFeatureClient_1,
  "@payloadcms/richtext-lexical/client#SubscriptFeatureClient": SubscriptFeatureClient_1,
  "@payloadcms/richtext-lexical/client#SuperscriptFeatureClient": SuperscriptFeatureClient_1,
  "@payloadcms/richtext-lexical/client#UnderlineFeatureClient": UnderlineFeatureClient_1,
  "@payloadcms/richtext-lexical/client#UnorderedListFeatureClient": UnorderedListFeatureClient_1,
  "@payloadcms/richtext-lexical/client#UploadFeatureClient": UploadFeatureClient_1,
};
