// Auto-generated by Payload CMS — maps admin.components / feature
// PayloadComponent string references to their actual imports. Payload's own
// `generate:importmap` CLI can't run in this project (richtext-lexical's
// top-level-await ESM export breaks the CLI's CJS require), so this is
// maintained by hand. Keys must exactly match the "path#ExportName" strings
// used in payload.config.ts / collection configs, and — for richText fields —
// the "ClientFeature" paths each @payloadcms/richtext-lexical feature
// registers internally (see node_modules/@payloadcms/richtext-lexical/dist/
// features/*/server/index.js). Missing feature entries fail silently on the
// client (no error, the field just never renders) instead of at build time.
import { AskaNav } from "@/components/admin/Nav";
import { Logo, Icon } from "@/components/admin/Logo";
import { AskaDashboard } from "@/components/admin/dashboard/AskaDashboard";
import { RichTextStyles } from "@/components/admin/RichTextStyles";
import { ViewBlogLink, ViewPageLink } from "@/components/admin/ViewLink";
import { EditPageVisuallyLink, EditTemplateVisuallyLink } from "@/components/admin/EditVisuallyLink";
import { RscEntryLexicalField, RscEntryLexicalCell, LexicalDiffComponent } from "@payloadcms/richtext-lexical/rsc";
import {
  AlignFeatureClient,
  BlockquoteFeatureClient,
  BlocksFeatureClient,
  ChecklistFeatureClient,
  FixedToolbarFeatureClient,
  HeadingFeatureClient,
  HorizontalRuleFeatureClient,
  IndentFeatureClient,
  InlineToolbarFeatureClient,
  LinkFeatureClient,
  OrderedListFeatureClient,
  ParagraphFeatureClient,
  RelationshipFeatureClient,
  UnorderedListFeatureClient,
  UploadFeatureClient,
} from "@payloadcms/richtext-lexical/client";

export const importMap = {
  "@/components/admin/Nav#AskaNav": AskaNav,
  "@/components/admin/Logo#Logo": Logo,
  "@/components/admin/Logo#Icon": Icon,
  "@/components/admin/dashboard/AskaDashboard#AskaDashboard": AskaDashboard,
  "@/components/admin/RichTextStyles#RichTextStyles": RichTextStyles,
  "@/components/admin/ViewLink#ViewBlogLink": ViewBlogLink,
  "@/components/admin/ViewLink#ViewPageLink": ViewPageLink,
  "@/components/admin/EditVisuallyLink#EditPageVisuallyLink": EditPageVisuallyLink,
  "@/components/admin/EditVisuallyLink#EditTemplateVisuallyLink": EditTemplateVisuallyLink,
  "@payloadcms/richtext-lexical/rsc#RscEntryLexicalField": RscEntryLexicalField,
  "@payloadcms/richtext-lexical/rsc#RscEntryLexicalCell": RscEntryLexicalCell,
  "@payloadcms/richtext-lexical/rsc#LexicalDiffComponent": LexicalDiffComponent,
  "@payloadcms/richtext-lexical/client#AlignFeatureClient": AlignFeatureClient,
  "@payloadcms/richtext-lexical/client#BlockquoteFeatureClient": BlockquoteFeatureClient,
  "@payloadcms/richtext-lexical/client#BlocksFeatureClient": BlocksFeatureClient,
  "@payloadcms/richtext-lexical/client#ChecklistFeatureClient": ChecklistFeatureClient,
  "@payloadcms/richtext-lexical/client#FixedToolbarFeatureClient": FixedToolbarFeatureClient,
  "@payloadcms/richtext-lexical/client#HeadingFeatureClient": HeadingFeatureClient,
  "@payloadcms/richtext-lexical/client#HorizontalRuleFeatureClient": HorizontalRuleFeatureClient,
  "@payloadcms/richtext-lexical/client#IndentFeatureClient": IndentFeatureClient,
  "@payloadcms/richtext-lexical/client#InlineToolbarFeatureClient": InlineToolbarFeatureClient,
  "@payloadcms/richtext-lexical/client#LinkFeatureClient": LinkFeatureClient,
  "@payloadcms/richtext-lexical/client#OrderedListFeatureClient": OrderedListFeatureClient,
  "@payloadcms/richtext-lexical/client#ParagraphFeatureClient": ParagraphFeatureClient,
  "@payloadcms/richtext-lexical/client#RelationshipFeatureClient": RelationshipFeatureClient,
  "@payloadcms/richtext-lexical/client#UnorderedListFeatureClient": UnorderedListFeatureClient,
  "@payloadcms/richtext-lexical/client#UploadFeatureClient": UploadFeatureClient,
};
